# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: SAST
  jobs:
  - job: SAST
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
      displayName: 'Build'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonarCloud'
        organization: 'lab-final'
        projectKey: 'Lab-Final_spring-boot-kubernetes'
        projectName: 'spring-boot-kubernetes'
      displayName: 'Preparacion Analisis SAST'
      
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'
      displayName: Analsis SAST

    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
      displayName: Publicacion resultado

    - task: sonarcloud-buildbreaker@2
      inputs:
        SonarCloud: 'sonarCloud'
        organization: 'lab-final'
      displayName: Break por QG


