# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: SAST
  jobs:
  - job: 
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
      displayName: 'Build'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonarCloud'
        organization: 'lab-final'
        projectKey: 'Lab-Final_spring-boot-kubernetes'
        projectName: 'spring-boot-kubernetes'
      displayName: 'Preparacion Analisis SAST'
      
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'
      displayName: Analsis SAST

    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
      displayName: Publicacion resultado

    - task: sonarcloud-buildbreaker@2
      inputs:
        SonarCloud: 'sonarCloud'
        organization: 'lab-final'
      displayName: Break por QG

- stage: ContainerSecurity 
  jobs:
  - job: Container_Security
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
        
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-lab'
        command: 'login'
        
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-lab'
        repository: 'lytch000/spring-boot-kubernetes'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
        
    - script: |
            sudo apt-get install -y rpm
            wget https://github.com/aquasecurity/trivy/releases/download/v0.27.1/trivy_0.27.1_Linux-64bit.deb
            sudo dpkg -i trivy_0.27.1_Linux-64bit.deb
            trivy image lytch000/spring-boot-kubernetes:latest
      displayName: Image Scan
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-lab'
        repository: 'lytch000/spring-boot-kubernetes'
        command: 'push'
        tags: 'latest'
      displayName: Docker Push
